import React,{useEffect,useState} from 'react';
import {DashboardIcon as Icon} from './DashboardIcons.jsx';
import {remoteRequest,devicePath,stamp,downloadRemoteApk} from './remoteTransport.js';
import {deviceId,deviceName,matchesDevice,needsAttention,phoneLine,relativeTime} from './kioskDeviceUtils.js';

export function FleetBrowser({devices,selected,onSelect,onEnroll,onPhoneLines,online}) {
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('all');
  const markets=[...new Set(devices.map(device=>device.market).filter(Boolean))];
  const summaries=[['Managed apps',devices.length,'Enrolled with this laptop','all','monitor'],['Online',devices.filter(item=>online && item.online).length,'Reporting to the service','online','signal'],['Phone lines',devices.filter(item=>phoneLine(item).number).length,'Reported or manual fallback','lines','phone'],['Needs attention',devices.filter(item=>needsAttention({...item,online:online && item.online})).length,'Connection, permissions, or playback','attention','warning'],['Unassigned',devices.filter(item=>!item.stationId).length,'Prepared for later assignment','unassigned','folder']];
  const displayed=devices.filter(item=>matchesDevice({...item,online:online && item.online},query,filter));
  return <section className="kc-fleet" aria-label="Enrolled Android apps"><details className="kc-fleet-browser"><summary><Icon name="monitor" size={18}/><strong>Managed apps</strong><span>{devices.length} enrolled · {devices.filter(item=>online && item.online).length} online</span><small>Browse, filter & phone lines</small></summary><div className="kc-summary-grid">{summaries.map(([label,value,detail,key,icon])=><button key={key} className={`kc-summary ${filter===key?'selected':''}`} onClick={()=>key==='lines'?onPhoneLines():setFilter(key)}><span><Icon name={icon} size={18}/>{label}</span><strong>{value}</strong><small>{detail}</small></button>)}<button className="kc-summary kc-add-device" onClick={onEnroll}><Icon name="plus" size={24}/><strong>Add an app</strong><small>Prepare or assign an Android device</small></button></div><div className="kc-fleet-tools"><label className="kc-search-box"><Icon name="search" size={18}/><input aria-label="Search enrolled apps" placeholder="Search station, name, model, device ID, carrier, or phone number" value={query} onChange={event=>setQuery(event.target.value)}/></label><span>{displayed.length} of {devices.length} apps</span></div><div className="kc-filter-row" aria-label="Filter enrolled apps">{[['all','All'],['unassigned','Unassigned'],...markets.map(market=>[`market:${market}`,market==='LAB'?'Laptop lab':market]),['attention','Needs attention'],['terminal','Kiosk app installed'],['no-terminal','App not installed']].map(([key,label])=><button key={key} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{label}</button>)}</div><div className="kc-fleet-grid">{displayed.map(device=><button key={deviceId(device)} className={`kc-device-card ${selected===deviceId(device)?'selected':''}`} onClick={()=>onSelect(deviceId(device))}><div><strong>{deviceName(device)}</strong><span className={`kc-pill ${online && device.online?'green':'amber'}`}>{online && device.online?'Online':'Offline'}</span></div><p>{device.displayName && device.stationId?`${device.displayName} · `:''}{[device.inventory?.manufacturer,device.inventory?.model].filter(Boolean).join(' ') || 'Model not reported'}</p><small>{device.market || 'Market not reported'} · {deviceId(device).slice(-12)}</small><footer><span>{!device.stationId?'Unassigned':device.inventory?.terminalLockdownActive===true?'App locked':device.inventory?.terminalPackageInstalled===true?'Kiosk app installed':'App status not reported'}</span><span>{relativeTime(device.lastSeenAt)}</span></footer></button>)}</div>{!displayed.length && <p className="kc-empty">{devices.length?'No apps match these filters.':'No apps enrolled yet. Add an app to begin.'}</p>}</details></section>;
}

export function AssignmentCard({device,stations,onSaved,disabled}) {
  const [stationId,setStationId]=useState(device.stationId || ''),[name,setName]=useState(device.displayName || ''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const signature=JSON.stringify([deviceId(device),device.stationId,device.displayName]);
  useEffect(()=>{setStationId(device.stationId || '');setName(device.displayName || '');setError('');setMessage('');},[signature]);
  async function save(event){event.preventDefault();setBusy(true);setError('');setMessage('');try{await remoteRequest(`${devicePath(device)}/assignment`,{stationId,market:'LAB',displayName:name.trim()});setMessage('Assignment saved to the local service.');onSaved();}catch(failure){setError(failure.message);}finally{setBusy(false);}}
  return <details className="kc-assignment"><summary><Icon name="folder" size={16}/>Assignment & display name <span>{device.stationId || 'Unassigned'} · {device.market || 'LAB'}</span></summary><form onSubmit={save}><p className="kc-description">Prepare the app without a station, or assign it to an available local kiosk. Production stations are not connected to this workspace.</p><div className="kc-assignment-fields"><label className="kc-field"><span>Market</span><select value="LAB" disabled><option value="LAB">Laptop lab</option></select></label><label className="kc-field"><span>Kiosk</span><select value={stationId} onChange={event=>setStationId(event.target.value)}><option value="">Unassigned · prepare for later</option>{stations.map(station=><option key={station.id} value={station.id} disabled={!!station.assignedDeviceId && station.assignedDeviceId!==deviceId(device)}>{station.id} · {station.name}{station.assignedDeviceId && station.assignedDeviceId!==deviceId(device)?' · Already assigned':''}</option>)}</select></label><label className="kc-field"><span>Display name</span><input value={name} maxLength={80} onChange={event=>setName(event.target.value)} placeholder="Optional device name"/></label><button className="kc-button blue" disabled={disabled || busy}>{busy?'Saving…':'Save assignment'}</button></div>{error && <p role="alert" className="kc-inline-error">{error}</p>}{message && <p role="status" className="kc-description">{message}</p>}</form></details>;
}

export function PhoneLinesModal({devices,onClose,onSelect,onSaved,online}) {
  const [query,setQuery]=useState(''),[editing,setEditing]=useState(null),[number,setNumber]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const withLine=devices.filter(device=>phoneLine(device).number);
  const counts=new Map();for(const device of withLine){const key=phoneLine(device).key;counts.set(key,(counts.get(key)||0)+1);}
  const rows=devices.filter(device=>matchesDevice(device,query));
  async function save(event){event.preventDefault();setBusy(true);setError('');try{await remoteRequest(`${devicePath(editing)}/phone-number`,{phoneNumber:number.trim()});setEditing(null);onSaved();}catch(failure){setError(failure.message);}finally{setBusy(false);}}
  return <div className="kc-modal-backdrop"><section className="kc-modal kc-wide-modal" role="dialog" aria-modal="true" aria-labelledby="kc-lines-title"><div className="kc-card-heading"><div><h2 id="kc-lines-title">Phone lines</h2><p>SIM numbers reported by Android, with a manual fallback when unavailable.</p></div><button className="kc-button" onClick={onClose} aria-label="Close phone lines"><Icon name="close" size={18}/></button></div><div className="kc-line-totals"><span><strong>{withLine.length}</strong> lines</span><span><strong>{withLine.filter(item=>online && item.online).length}</strong> online</span><span><strong>{withLine.filter(item=>!online || !item.online).length}</strong> offline</span><span><strong>{devices.length-withLine.length}</strong> unavailable</span><span><strong>{[...counts.values()].filter(value=>value>1).length}</strong> duplicated numbers</span></div><label className="kc-search-box"><Icon name="search" size={18}/><input aria-label="Search phone lines" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search phone number, station, model, or carrier"/></label><div className="kc-phone-lines">{rows.map(device=>{const line=phoneLine(device);return <article key={deviceId(device)}><div className="kc-line-main"><button className="kc-text-button" onClick={()=>{onSelect(deviceId(device));onClose();}}>{deviceName(device)}</button><strong>{line.number || 'Number unavailable'}</strong><small>{device.inventory?.cellularCarrier || 'Carrier not reported'} · {device.inventory?.model || deviceId(device)}</small><small>{online && device.online?'Online':'Offline'} · Last seen {relativeTime(device.lastSeenAt)}</small></div><div className="kc-line-actions">{line.source && <span className="kc-pill">{line.source==='agent'?'Android reported':'Manual fallback'}</span>}{counts.get(line.key)>1 && <span className="kc-pill amber">Duplicate</span>}{line.agent?<small>Reported numbers are retained and cannot be overwritten here.</small>:<button className="kc-button" disabled={!online || busy} onClick={()=>{setEditing(device);setNumber(line.manual);setError('');}}><Icon name="text" size={15}/>{line.manual?'Edit number':'Add fallback'}</button>}</div></article>;})}{!rows.length && <p className="kc-empty">No matching devices.</p>}</div>{editing && <form className="kc-line-editor" onSubmit={save}><h3>Manual fallback · {deviceName(editing)}</h3><label className="kc-field"><span>Phone number · leave blank to remove</span><input type="tel" value={number} onChange={event=>setNumber(event.target.value)} maxLength={32} placeholder="+1 555 123 4567"/></label><div className="kc-button-row"><button type="button" className="kc-button" onClick={()=>setEditing(null)}>Cancel</button><button className="kc-button primary" disabled={busy}>{busy?'Saving…':number.trim()?'Save fallback':'Remove fallback'}</button></div>{error && <p className="kc-inline-error" role="alert">{error}</p>}</form>}</section></div>;
}

export function EnrollmentModal({stations,online,onClose}) {
  const [mode,setMode]=useState('prepare'),[stationId,setStationId]=useState('LAB-US8004'),[name,setName]=useState('');
  const [enrollment,setEnrollment]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function create(event){event.preventDefault();setBusy(true);setError('');try{setEnrollment(await remoteRequest('/enrollments',{stationId:mode==='prepare'?'':stationId,market:'LAB',displayName:name.trim()}));}catch(failure){setError(failure.message);}finally{setBusy(false);}}
  return <div className="kc-modal-backdrop"><section className="kc-modal kc-wide-modal" role="dialog" aria-modal="true" aria-labelledby="kc-enroll-title"><div className="kc-card-heading"><div><span className="kc-pill purple">Local enrollment</span><h2 id="kc-enroll-title">Add an Android app</h2></div><button className="kc-button" onClick={onClose} aria-label="Close enrollment"><Icon name="close" size={18}/></button></div><div className="kc-enroll-grid"><form onSubmit={create}><h3>1. Prepare or assign the app</h3><label className="kc-field"><span>Enrollment</span><select value={mode} onChange={event=>setMode(event.target.value)}><option value="prepare">Prepare now · assign later</option><option value="assign">Assign to a local kiosk now</option></select></label><label className="kc-field"><span>Market</span><select disabled value="LAB"><option value="LAB">Laptop lab</option></select></label>{mode==='assign' && <label className="kc-field"><span>Kiosk</span><select value={stationId} onChange={event=>setStationId(event.target.value)}>{stations.map(station=><option key={station.id} value={station.id} disabled={!!station.assignedDeviceId}>{station.id} · {station.name}{station.assignedDeviceId?' · Already assigned':''}</option>)}</select></label>}<label className="kc-field"><span>Display name</span><input value={name} maxLength={80} onChange={event=>setName(event.target.value)} placeholder="Optional device name"/></label><button className="kc-button primary" disabled={!online || busy || (mode==='assign' && (!stationId || !stations.some(station=>station.id===stationId && !station.assignedDeviceId)))}>{busy?'Creating…':enrollment?'Create another code':'Create enrollment code'}</button>{error && <p role="alert" className="kc-inline-error">{error}</p>}{enrollment && <><div className="kc-enrollment-code">{enrollment.enrollmentCode}</div><p className="kc-small-note">{enrollment.stationId || 'Unassigned'} · Expires {stamp(enrollment.expiresAt)}. Use this code once.</p></>}</form><div><h3>2. Connect in the Android app</h3><ol className="kc-setup-steps"><li>Install the integrated kiosk APK for this local workspace.</li><li>Open Staff controls (PIN 2468), then Remote management setup.</li><li>Enter the device enrollment code and enroll.</li><li>Enable Accessibility for remote input. Device Owner setup is needed for system controls.</li></ol><p className="kc-small-note">The emulator reaches this laptop through its configured local address. Other Android hardware needs a reachable setup service; a localhost URL on that device points to the device itself.</p><LocalSetup/></div></div></section></div>;
}

function LocalSetup() {
  const [setup,setSetup]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{let ignore=false;remoteRequest('/provisioning').then(value=>{if(!ignore)setSetup(value);}).catch(failure=>{if(!ignore)setError(failure.message);});return()=>{ignore=true;};},[]);
  function saveBlob(blob,name){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
  async function download(){setBusy(true);setError('');try{saveBlob(await downloadRemoteApk(),`chargerent-kiosk-${setup?.release?.versionName || 'local'}.apk`);}catch(failure){setError(failure.message);}finally{setBusy(false);}}
  return <details className="kc-local-setup"><summary><Icon name="qr" size={17}/>APK download & Device Owner setup</summary>{setup?.release && <p className="kc-description">Local APK: v{setup.release.versionName} · {setup.packageName}</p>}<div className="kc-button-row"><button type="button" className="kc-button blue" disabled={!setup || busy} onClick={download}><Icon name="download" size={16}/>{busy?'Downloading…':'Download local APK'}</button>{setup?.payload && <button type="button" className="kc-button" onClick={()=>saveBlob(new Blob([JSON.stringify(setup.payload,null,2)],{type:'application/json'}),'kiosk-local-provisioning.json')}>Setup JSON</button>}</div><p className="kc-description"><strong>Factory setup QR: {setup?.available?'Available':'Not available for this local setup'}</strong></p><p className="kc-description">{setup?.reason || 'Checking the service’s setup availability…'}</p>{setup?.deviceAdminComponent && <p className="kc-small-note">Device admin: {setup.deviceAdminComponent}</p>}{error && <p className="kc-inline-error">{error}</p>}<p className="kc-small-note">This APK contains the kiosk’s media, payment simulation, and remote controls. Factory setup needs a reachable, approved download URL; the existing Phone Control QR installs a different app.</p></details>;
}
